//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecturerCompare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lec_Rank
    {
        public int Lec_Id { get; set; }
        public int Rank_Id { get; set; }
        public int rank { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Lecturers Lecturers { get; set; }
        public virtual Rank_Types Rank_Types { get; set; }
    }
}
