//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecturerCompare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schools
    {
        public Schools()
        {
            this.Lecturers = new HashSet<Lecturers>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Lecturers> Lecturers { get; set; }
    }
}
